import streamlit as st
import pandas as pd
import glob
import os
from datetime import datetime

# 1. Page Configuration (Professional UI)
st.set_page_config(
    page_title="Nifty 500 Algo-Screener",
    page_icon="📈",
    layout="wide"
)

st.title("📈 Nifty 500 Algorithmic Dashboard")
st.markdown("""
    This dashboard serves processed data from an automated ETL pipeline. 
    It filters for high-probability setups based on **NVI (Negative Volume Indicator)** and **Stochastic RSI**.
""")

# 2. Data Loading Engine (The "Data Engineering" Part)
def load_latest_data():
    """Finds the most recent CSV file generated by the GitHub Action."""
    # This matches the filename pattern in your Stock_screener_nifty.py
    list_of_files = glob.glob('Nifty500_Scan_*.csv')
    
    if not list_of_files:
        return None
    
    # Get the file with the most recent creation time
    latest_file = max(list_of_files, key=os.path.getctime)
    df = pd.read_csv(latest_file)
    return df, latest_file

# Execute Load
data_result = load_latest_data()

# 3. UI Logic
if data_result is None:
    st.error("🚨 **No Data Found:** The ETL pipeline hasn't generated a CSV yet, or the filename pattern doesn't match.")
    st.info("Ensure your GitHub Action has run successfully and pushed a file named `Nifty500_Scan_...csv` to the repository.")
else:
    df, filename = data_result
    
    # Extract timestamp from filename for the UI
    st.caption(f"Last Pipeline Run: `{filename}` | Stocks Processed: {len(df)}")

    # --- SIDEBAR FILTERS ---
    st.sidebar.header("🎯 Strategy Filters")
    
    st.sidebar.subheader("1D Stochastic RSI")
    stoch_limit = st.sidebar.slider("Max Stoch K (Oversold < 20)", 0, 100, 20)
    
    st.sidebar.subheader("Momentum Settings")
    show_bullish_macd = st.sidebar.checkbox("15m MACD Bullish Crossover", value=True)
    
    st.sidebar.subheader("Volume Trend")
    nvi_filter = st.sidebar.checkbox("NVI Above EMA (Long-term Accumulation)")

    # --- FILTERING LOGIC ---
    # Apply Stochastic Filter
    filtered_df = df[df['1D_Stoch_K_Black'] <= stoch_limit]
    
    # Apply MACD Filter
    if show_bullish_macd:
        filtered_df = filtered_df[filtered_df['15m_MACD_Black'] > filtered_df['15m_MACD_Red']]
        
    # Apply NVI Filter
    if nvi_filter:
        filtered_df = filtered_df[filtered_df['1D_NVI_Black'] > filtered_df['1D_NVI_Red']]

    # --- MAIN DISPLAY ---
    col1, col2, col3 = st.columns(3)
    col1.metric("Total Stocks", len(df))
    col2.metric("Filtered Results", len(filtered_df))
    col3.metric("Last Update", datetime.now().strftime("%H:%M IST"))

    st.subheader(f"Filtered Setups ({len(filtered_df)})")
    
    if not filtered_df.empty:
        # Display the data with high-visibility columns
        st.dataframe(
            filtered_df[[
                'Ticker', '1D_Price', '1D_Stoch_K_Black', 
                '1D_NVI_Black', '1D_NVI_Red', 
                '15m_MACD_Black', '15m_MACD_Red'
            ]],
            use_container_width=True,
            hide_index=True
        )
        
        # Download Button (Great for User Experience)
        csv_data = filtered_df.to_csv(index=False).encode('utf-8')
        st.download_button(
            label="📥 Download Filtered Results as CSV",
            data=csv_data,
            file_name=f"Filtered_Stocks_{datetime.now().strftime('%Y%m%d')}.csv",
            mime="text/csv",
        )
    else:
        st.warning("No stocks currently match these specific filter criteria. Try easing the filters in the sidebar.")

    # Expander for Raw Data (For Debugging/Transparency)
    with st.expander("🔍 View Raw Pipeline Output"):
        st.write(df)
